services:
  node-app:
    image: node:16 # Utilisation de l'image Node.js version 16 (tu peux choisir la version que tu souhaites)
    container_name: node_server
    working_dir: /usr/src/app/
    volumes:
      - ./dist:/usr/src/app # Monte le répertoire actuel dans /usr/src/app dans le conteneur
    ports:
      - "3000:3000" # Expose le port 3000 à l'extérieur (tu peux changer si nécessaire)
    command: "npm start" # Commande à exécuter (dépend de ton script start dans package.json)
    environment:
      NODE_ENV: development
